// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/api.proto

It has these top-level messages:
	Client
	Connector
	ListConnectorResp
	ListConnectorReq
	DeleteConnectorReq
	DeleteConnectorResp
	CreateClientReq
	CreateClientResp
	DeleteClientReq
	DeleteClientResp
	UpdateClientReq
	UpdateClientResp
	Password
	CreatePasswordReq
	CreatePasswordResp
	UpdatePasswordReq
	UpdatePasswordResp
	DeletePasswordReq
	DeletePasswordResp
	ListPasswordReq
	ListPasswordResp
	VersionReq
	VersionResp
	RefreshTokenRef
	ListRefreshReq
	ListRefreshResp
	RevokeRefreshReq
	RevokeRefreshResp
	VerifyPasswordReq
	VerifyPasswordResp
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Client represents an OAuth2 client.
type Client struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Secret       string   `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	RedirectUris []string `protobuf:"bytes,3,rep,name=redirect_uris,json=redirectUris" json:"redirect_uris,omitempty"`
	TrustedPeers []string `protobuf:"bytes,4,rep,name=trusted_peers,json=trustedPeers" json:"trusted_peers,omitempty"`
	Public       bool     `protobuf:"varint,5,opt,name=public" json:"public,omitempty"`
	Name         string   `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	LogoUrl      string   `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl" json:"logo_url,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Client) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *Client) GetTrustedPeers() []string {
	if m != nil {
		return m.TrustedPeers
	}
	return nil
}

func (m *Client) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

// Connector represents a mechanism for enabling login to dex via an identity service
type Connector struct {
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Config []byte `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *Connector) Reset()                    { *m = Connector{} }
func (m *Connector) String() string            { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()               {}
func (*Connector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Connector) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Connector) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Connector) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Connector) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

// ListRefreshResp returns a list of refresh tokens for a user.
type ListConnectorResp struct {
	Connectors []*Connector `protobuf:"bytes,1,rep,name=connectors" json:"connectors,omitempty"`
}

func (m *ListConnectorResp) Reset()                    { *m = ListConnectorResp{} }
func (m *ListConnectorResp) String() string            { return proto.CompactTextString(m) }
func (*ListConnectorResp) ProtoMessage()               {}
func (*ListConnectorResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListConnectorResp) GetConnectors() []*Connector {
	if m != nil {
		return m.Connectors
	}
	return nil
}

// ListConnectorReq is a request to enumerate connectors.
type ListConnectorReq struct {
}

func (m *ListConnectorReq) Reset()                    { *m = ListConnectorReq{} }
func (m *ListConnectorReq) String() string            { return proto.CompactTextString(m) }
func (*ListConnectorReq) ProtoMessage()               {}
func (*ListConnectorReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// DeleteConnectorReq is a request to delete a connector with the given ID.
type DeleteConnectorReq struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteConnectorReq) Reset()                    { *m = DeleteConnectorReq{} }
func (m *DeleteConnectorReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteConnectorReq) ProtoMessage()               {}
func (*DeleteConnectorReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteConnectorReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteConnectorResp struct {
}

func (m *DeleteConnectorResp) Reset()                    { *m = DeleteConnectorResp{} }
func (m *DeleteConnectorResp) String() string            { return proto.CompactTextString(m) }
func (*DeleteConnectorResp) ProtoMessage()               {}
func (*DeleteConnectorResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// CreateClientReq is a request to make a client.
type CreateClientReq struct {
	Client *Client `protobuf:"bytes,1,opt,name=client" json:"client,omitempty"`
}

func (m *CreateClientReq) Reset()                    { *m = CreateClientReq{} }
func (m *CreateClientReq) String() string            { return proto.CompactTextString(m) }
func (*CreateClientReq) ProtoMessage()               {}
func (*CreateClientReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateClientReq) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

// CreateClientResp returns the response from creating a client.
type CreateClientResp struct {
	AlreadyExists bool    `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists" json:"already_exists,omitempty"`
	Client        *Client `protobuf:"bytes,2,opt,name=client" json:"client,omitempty"`
}

func (m *CreateClientResp) Reset()                    { *m = CreateClientResp{} }
func (m *CreateClientResp) String() string            { return proto.CompactTextString(m) }
func (*CreateClientResp) ProtoMessage()               {}
func (*CreateClientResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateClientResp) GetAlreadyExists() bool {
	if m != nil {
		return m.AlreadyExists
	}
	return false
}

func (m *CreateClientResp) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

// DeleteClientReq is a request to delete a client.
type DeleteClientReq struct {
	// The ID of the client.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteClientReq) Reset()                    { *m = DeleteClientReq{} }
func (m *DeleteClientReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteClientReq) ProtoMessage()               {}
func (*DeleteClientReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteClientReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// DeleteClientResp determines if the client is deleted successfully.
type DeleteClientResp struct {
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *DeleteClientResp) Reset()                    { *m = DeleteClientResp{} }
func (m *DeleteClientResp) String() string            { return proto.CompactTextString(m) }
func (*DeleteClientResp) ProtoMessage()               {}
func (*DeleteClientResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteClientResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

// UpdateClientReq is a request to update an exisitng client.
type UpdateClientReq struct {
	Id           string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RedirectUris []string `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris" json:"redirect_uris,omitempty"`
	TrustedPeers []string `protobuf:"bytes,3,rep,name=trusted_peers,json=trustedPeers" json:"trusted_peers,omitempty"`
	Name         string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	LogoUrl      string   `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl" json:"logo_url,omitempty"`
}

func (m *UpdateClientReq) Reset()                    { *m = UpdateClientReq{} }
func (m *UpdateClientReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateClientReq) ProtoMessage()               {}
func (*UpdateClientReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateClientReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateClientReq) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *UpdateClientReq) GetTrustedPeers() []string {
	if m != nil {
		return m.TrustedPeers
	}
	return nil
}

func (m *UpdateClientReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateClientReq) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

// UpdateClientResp returns the reponse form updating a client.
type UpdateClientResp struct {
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *UpdateClientResp) Reset()                    { *m = UpdateClientResp{} }
func (m *UpdateClientResp) String() string            { return proto.CompactTextString(m) }
func (*UpdateClientResp) ProtoMessage()               {}
func (*UpdateClientResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateClientResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

// Password is an email for password mapping managed by the storage.
type Password struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	// Currently we do not accept plain text passwords. Could be an option in the future.
	Hash     []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	UserId   string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Password) Reset()                    { *m = Password{} }
func (m *Password) String() string            { return proto.CompactTextString(m) }
func (*Password) ProtoMessage()               {}
func (*Password) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Password) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Password) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Password) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Password) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// CreatePasswordReq is a request to make a password.
type CreatePasswordReq struct {
	Password *Password `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *CreatePasswordReq) Reset()                    { *m = CreatePasswordReq{} }
func (m *CreatePasswordReq) String() string            { return proto.CompactTextString(m) }
func (*CreatePasswordReq) ProtoMessage()               {}
func (*CreatePasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CreatePasswordReq) GetPassword() *Password {
	if m != nil {
		return m.Password
	}
	return nil
}

// CreatePasswordResp returns the response from creating a password.
type CreatePasswordResp struct {
	AlreadyExists bool `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists" json:"already_exists,omitempty"`
}

func (m *CreatePasswordResp) Reset()                    { *m = CreatePasswordResp{} }
func (m *CreatePasswordResp) String() string            { return proto.CompactTextString(m) }
func (*CreatePasswordResp) ProtoMessage()               {}
func (*CreatePasswordResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreatePasswordResp) GetAlreadyExists() bool {
	if m != nil {
		return m.AlreadyExists
	}
	return false
}

// UpdatePasswordReq is a request to modify an existing password.
type UpdatePasswordReq struct {
	// The email used to lookup the password. This field cannot be modified
	Email       string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	NewHash     []byte `protobuf:"bytes,2,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	NewUsername string `protobuf:"bytes,3,opt,name=new_username,json=newUsername" json:"new_username,omitempty"`
}

func (m *UpdatePasswordReq) Reset()                    { *m = UpdatePasswordReq{} }
func (m *UpdatePasswordReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordReq) ProtoMessage()               {}
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UpdatePasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatePasswordReq) GetNewHash() []byte {
	if m != nil {
		return m.NewHash
	}
	return nil
}

func (m *UpdatePasswordReq) GetNewUsername() string {
	if m != nil {
		return m.NewUsername
	}
	return ""
}

// UpdatePasswordResp returns the response from modifying an existing password.
type UpdatePasswordResp struct {
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *UpdatePasswordResp) Reset()                    { *m = UpdatePasswordResp{} }
func (m *UpdatePasswordResp) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordResp) ProtoMessage()               {}
func (*UpdatePasswordResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdatePasswordResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

// DeletePasswordReq is a request to delete a password.
type DeletePasswordReq struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *DeletePasswordReq) Reset()                    { *m = DeletePasswordReq{} }
func (m *DeletePasswordReq) String() string            { return proto.CompactTextString(m) }
func (*DeletePasswordReq) ProtoMessage()               {}
func (*DeletePasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *DeletePasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// DeletePasswordResp returns the response from deleting a password.
type DeletePasswordResp struct {
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *DeletePasswordResp) Reset()                    { *m = DeletePasswordResp{} }
func (m *DeletePasswordResp) String() string            { return proto.CompactTextString(m) }
func (*DeletePasswordResp) ProtoMessage()               {}
func (*DeletePasswordResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DeletePasswordResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

// ListPasswordReq is a request to enumerate passwords.
type ListPasswordReq struct {
}

func (m *ListPasswordReq) Reset()                    { *m = ListPasswordReq{} }
func (m *ListPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*ListPasswordReq) ProtoMessage()               {}
func (*ListPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

// ListPasswordResp returns a list of passwords.
type ListPasswordResp struct {
	Passwords []*Password `protobuf:"bytes,1,rep,name=passwords" json:"passwords,omitempty"`
}

func (m *ListPasswordResp) Reset()                    { *m = ListPasswordResp{} }
func (m *ListPasswordResp) String() string            { return proto.CompactTextString(m) }
func (*ListPasswordResp) ProtoMessage()               {}
func (*ListPasswordResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListPasswordResp) GetPasswords() []*Password {
	if m != nil {
		return m.Passwords
	}
	return nil
}

// VersionReq is a request to fetch version info.
type VersionReq struct {
}

func (m *VersionReq) Reset()                    { *m = VersionReq{} }
func (m *VersionReq) String() string            { return proto.CompactTextString(m) }
func (*VersionReq) ProtoMessage()               {}
func (*VersionReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

// VersionResp holds the version info of components.
type VersionResp struct {
	// Semantic version of the server.
	Server string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	// Numeric version of the API. It increases everytime a new call is added to the API.
	// Clients should use this info to determine if the server supports specific features.
	Api int32 `protobuf:"varint,2,opt,name=api" json:"api,omitempty"`
}

func (m *VersionResp) Reset()                    { *m = VersionResp{} }
func (m *VersionResp) String() string            { return proto.CompactTextString(m) }
func (*VersionResp) ProtoMessage()               {}
func (*VersionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *VersionResp) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *VersionResp) GetApi() int32 {
	if m != nil {
		return m.Api
	}
	return 0
}

// RefreshTokenRef contains the metadata for a refresh token that is managed by the storage.
type RefreshTokenRef struct {
	// ID of the refresh token.
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ClientId  string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	CreatedAt int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	LastUsed  int64  `protobuf:"varint,6,opt,name=last_used,json=lastUsed" json:"last_used,omitempty"`
}

func (m *RefreshTokenRef) Reset()                    { *m = RefreshTokenRef{} }
func (m *RefreshTokenRef) String() string            { return proto.CompactTextString(m) }
func (*RefreshTokenRef) ProtoMessage()               {}
func (*RefreshTokenRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RefreshTokenRef) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefreshTokenRef) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RefreshTokenRef) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *RefreshTokenRef) GetLastUsed() int64 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

// ListRefreshReq is a request to enumerate the refresh tokens of a user.
type ListRefreshReq struct {
	// The "sub" claim returned in the ID Token.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *ListRefreshReq) Reset()                    { *m = ListRefreshReq{} }
func (m *ListRefreshReq) String() string            { return proto.CompactTextString(m) }
func (*ListRefreshReq) ProtoMessage()               {}
func (*ListRefreshReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ListRefreshReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// ListRefreshResp returns a list of refresh tokens for a user.
type ListRefreshResp struct {
	RefreshTokens []*RefreshTokenRef `protobuf:"bytes,1,rep,name=refresh_tokens,json=refreshTokens" json:"refresh_tokens,omitempty"`
}

func (m *ListRefreshResp) Reset()                    { *m = ListRefreshResp{} }
func (m *ListRefreshResp) String() string            { return proto.CompactTextString(m) }
func (*ListRefreshResp) ProtoMessage()               {}
func (*ListRefreshResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListRefreshResp) GetRefreshTokens() []*RefreshTokenRef {
	if m != nil {
		return m.RefreshTokens
	}
	return nil
}

// RevokeRefreshReq is a request to revoke the refresh token of the user-client pair.
type RevokeRefreshReq struct {
	// The "sub" claim returned in the ID Token.
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

func (m *RevokeRefreshReq) Reset()                    { *m = RevokeRefreshReq{} }
func (m *RevokeRefreshReq) String() string            { return proto.CompactTextString(m) }
func (*RevokeRefreshReq) ProtoMessage()               {}
func (*RevokeRefreshReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *RevokeRefreshReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RevokeRefreshReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// RevokeRefreshResp determines if the refresh token is revoked successfully.
type RevokeRefreshResp struct {
	// Set to true is refresh token was not found and token could not be revoked.
	NotFound bool `protobuf:"varint,1,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *RevokeRefreshResp) Reset()                    { *m = RevokeRefreshResp{} }
func (m *RevokeRefreshResp) String() string            { return proto.CompactTextString(m) }
func (*RevokeRefreshResp) ProtoMessage()               {}
func (*RevokeRefreshResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RevokeRefreshResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type VerifyPasswordReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *VerifyPasswordReq) Reset()                    { *m = VerifyPasswordReq{} }
func (m *VerifyPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*VerifyPasswordReq) ProtoMessage()               {}
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *VerifyPasswordReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyPasswordResp struct {
	Verified bool `protobuf:"varint,1,opt,name=verified" json:"verified,omitempty"`
	NotFound bool `protobuf:"varint,2,opt,name=not_found,json=notFound" json:"not_found,omitempty"`
}

func (m *VerifyPasswordResp) Reset()                    { *m = VerifyPasswordResp{} }
func (m *VerifyPasswordResp) String() string            { return proto.CompactTextString(m) }
func (*VerifyPasswordResp) ProtoMessage()               {}
func (*VerifyPasswordResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *VerifyPasswordResp) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *VerifyPasswordResp) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func init() {
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*Connector)(nil), "api.Connector")
	proto.RegisterType((*ListConnectorResp)(nil), "api.ListConnectorResp")
	proto.RegisterType((*ListConnectorReq)(nil), "api.ListConnectorReq")
	proto.RegisterType((*DeleteConnectorReq)(nil), "api.DeleteConnectorReq")
	proto.RegisterType((*DeleteConnectorResp)(nil), "api.DeleteConnectorResp")
	proto.RegisterType((*CreateClientReq)(nil), "api.CreateClientReq")
	proto.RegisterType((*CreateClientResp)(nil), "api.CreateClientResp")
	proto.RegisterType((*DeleteClientReq)(nil), "api.DeleteClientReq")
	proto.RegisterType((*DeleteClientResp)(nil), "api.DeleteClientResp")
	proto.RegisterType((*UpdateClientReq)(nil), "api.UpdateClientReq")
	proto.RegisterType((*UpdateClientResp)(nil), "api.UpdateClientResp")
	proto.RegisterType((*Password)(nil), "api.Password")
	proto.RegisterType((*CreatePasswordReq)(nil), "api.CreatePasswordReq")
	proto.RegisterType((*CreatePasswordResp)(nil), "api.CreatePasswordResp")
	proto.RegisterType((*UpdatePasswordReq)(nil), "api.UpdatePasswordReq")
	proto.RegisterType((*UpdatePasswordResp)(nil), "api.UpdatePasswordResp")
	proto.RegisterType((*DeletePasswordReq)(nil), "api.DeletePasswordReq")
	proto.RegisterType((*DeletePasswordResp)(nil), "api.DeletePasswordResp")
	proto.RegisterType((*ListPasswordReq)(nil), "api.ListPasswordReq")
	proto.RegisterType((*ListPasswordResp)(nil), "api.ListPasswordResp")
	proto.RegisterType((*VersionReq)(nil), "api.VersionReq")
	proto.RegisterType((*VersionResp)(nil), "api.VersionResp")
	proto.RegisterType((*RefreshTokenRef)(nil), "api.RefreshTokenRef")
	proto.RegisterType((*ListRefreshReq)(nil), "api.ListRefreshReq")
	proto.RegisterType((*ListRefreshResp)(nil), "api.ListRefreshResp")
	proto.RegisterType((*RevokeRefreshReq)(nil), "api.RevokeRefreshReq")
	proto.RegisterType((*RevokeRefreshResp)(nil), "api.RevokeRefreshResp")
	proto.RegisterType((*VerifyPasswordReq)(nil), "api.VerifyPasswordReq")
	proto.RegisterType((*VerifyPasswordResp)(nil), "api.VerifyPasswordResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dex service

type DexClient interface {
	// CreateClient creates a client.
	CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error)
	// UpdateClient updates an existing client
	UpdateClient(ctx context.Context, in *UpdateClientReq, opts ...grpc.CallOption) (*UpdateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error)
	// CreatePassword creates a password.
	CreatePassword(ctx context.Context, in *CreatePasswordReq, opts ...grpc.CallOption) (*CreatePasswordResp, error)
	// UpdatePassword modifies existing password.
	UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error)
	// DeletePassword deletes the password.
	DeletePassword(ctx context.Context, in *DeletePasswordReq, opts ...grpc.CallOption) (*DeletePasswordResp, error)
	// ListPassword lists all password entries.
	ListPasswords(ctx context.Context, in *ListPasswordReq, opts ...grpc.CallOption) (*ListPasswordResp, error)
	// GetVersion returns version information of the server.
	GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error)
	// ListRefresh lists all the refresh token entries for a particular user.
	ListRefresh(ctx context.Context, in *ListRefreshReq, opts ...grpc.CallOption) (*ListRefreshResp, error)
	// RevokeRefresh revokes the refresh token for the provided user-client pair.
	//
	// Note that each user-client pair can have only one refresh token at a time.
	RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error)
	// VerifyPassword returns whether a password matches a hash for a specific email or not.
	VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error)
	// Create Connector on the fly
	CreateConnector(ctx context.Context, in *Connector, opts ...grpc.CallOption) (*Connector, error)
	// Update Connector on the fly
	UpdateConnector(ctx context.Context, in *Connector, opts ...grpc.CallOption) (*Connector, error)
	// DeleteConnector deletes the corresponding connector
	DeleteConnector(ctx context.Context, in *DeleteConnectorReq, opts ...grpc.CallOption) (*DeleteConnectorResp, error)
	// ListConnector lists the available connectors
	ListConnector(ctx context.Context, in *ListConnectorReq, opts ...grpc.CallOption) (*ListConnectorResp, error)
}

type dexClient struct {
	cc *grpc.ClientConn
}

func NewDexClient(cc *grpc.ClientConn) DexClient {
	return &dexClient{cc}
}

func (c *dexClient) CreateClient(ctx context.Context, in *CreateClientReq, opts ...grpc.CallOption) (*CreateClientResp, error) {
	out := new(CreateClientResp)
	err := grpc.Invoke(ctx, "/api.Dex/CreateClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) UpdateClient(ctx context.Context, in *UpdateClientReq, opts ...grpc.CallOption) (*UpdateClientResp, error) {
	out := new(UpdateClientResp)
	err := grpc.Invoke(ctx, "/api.Dex/UpdateClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) DeleteClient(ctx context.Context, in *DeleteClientReq, opts ...grpc.CallOption) (*DeleteClientResp, error) {
	out := new(DeleteClientResp)
	err := grpc.Invoke(ctx, "/api.Dex/DeleteClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) CreatePassword(ctx context.Context, in *CreatePasswordReq, opts ...grpc.CallOption) (*CreatePasswordResp, error) {
	out := new(CreatePasswordResp)
	err := grpc.Invoke(ctx, "/api.Dex/CreatePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResp, error) {
	out := new(UpdatePasswordResp)
	err := grpc.Invoke(ctx, "/api.Dex/UpdatePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) DeletePassword(ctx context.Context, in *DeletePasswordReq, opts ...grpc.CallOption) (*DeletePasswordResp, error) {
	out := new(DeletePasswordResp)
	err := grpc.Invoke(ctx, "/api.Dex/DeletePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) ListPasswords(ctx context.Context, in *ListPasswordReq, opts ...grpc.CallOption) (*ListPasswordResp, error) {
	out := new(ListPasswordResp)
	err := grpc.Invoke(ctx, "/api.Dex/ListPasswords", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) GetVersion(ctx context.Context, in *VersionReq, opts ...grpc.CallOption) (*VersionResp, error) {
	out := new(VersionResp)
	err := grpc.Invoke(ctx, "/api.Dex/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) ListRefresh(ctx context.Context, in *ListRefreshReq, opts ...grpc.CallOption) (*ListRefreshResp, error) {
	out := new(ListRefreshResp)
	err := grpc.Invoke(ctx, "/api.Dex/ListRefresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) RevokeRefresh(ctx context.Context, in *RevokeRefreshReq, opts ...grpc.CallOption) (*RevokeRefreshResp, error) {
	out := new(RevokeRefreshResp)
	err := grpc.Invoke(ctx, "/api.Dex/RevokeRefresh", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) VerifyPassword(ctx context.Context, in *VerifyPasswordReq, opts ...grpc.CallOption) (*VerifyPasswordResp, error) {
	out := new(VerifyPasswordResp)
	err := grpc.Invoke(ctx, "/api.Dex/VerifyPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) CreateConnector(ctx context.Context, in *Connector, opts ...grpc.CallOption) (*Connector, error) {
	out := new(Connector)
	err := grpc.Invoke(ctx, "/api.Dex/CreateConnector", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) UpdateConnector(ctx context.Context, in *Connector, opts ...grpc.CallOption) (*Connector, error) {
	out := new(Connector)
	err := grpc.Invoke(ctx, "/api.Dex/UpdateConnector", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) DeleteConnector(ctx context.Context, in *DeleteConnectorReq, opts ...grpc.CallOption) (*DeleteConnectorResp, error) {
	out := new(DeleteConnectorResp)
	err := grpc.Invoke(ctx, "/api.Dex/DeleteConnector", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dexClient) ListConnector(ctx context.Context, in *ListConnectorReq, opts ...grpc.CallOption) (*ListConnectorResp, error) {
	out := new(ListConnectorResp)
	err := grpc.Invoke(ctx, "/api.Dex/ListConnector", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dex service

type DexServer interface {
	// CreateClient creates a client.
	CreateClient(context.Context, *CreateClientReq) (*CreateClientResp, error)
	// UpdateClient updates an existing client
	UpdateClient(context.Context, *UpdateClientReq) (*UpdateClientResp, error)
	// DeleteClient deletes the provided client.
	DeleteClient(context.Context, *DeleteClientReq) (*DeleteClientResp, error)
	// CreatePassword creates a password.
	CreatePassword(context.Context, *CreatePasswordReq) (*CreatePasswordResp, error)
	// UpdatePassword modifies existing password.
	UpdatePassword(context.Context, *UpdatePasswordReq) (*UpdatePasswordResp, error)
	// DeletePassword deletes the password.
	DeletePassword(context.Context, *DeletePasswordReq) (*DeletePasswordResp, error)
	// ListPassword lists all password entries.
	ListPasswords(context.Context, *ListPasswordReq) (*ListPasswordResp, error)
	// GetVersion returns version information of the server.
	GetVersion(context.Context, *VersionReq) (*VersionResp, error)
	// ListRefresh lists all the refresh token entries for a particular user.
	ListRefresh(context.Context, *ListRefreshReq) (*ListRefreshResp, error)
	// RevokeRefresh revokes the refresh token for the provided user-client pair.
	//
	// Note that each user-client pair can have only one refresh token at a time.
	RevokeRefresh(context.Context, *RevokeRefreshReq) (*RevokeRefreshResp, error)
	// VerifyPassword returns whether a password matches a hash for a specific email or not.
	VerifyPassword(context.Context, *VerifyPasswordReq) (*VerifyPasswordResp, error)
	// Create Connector on the fly
	CreateConnector(context.Context, *Connector) (*Connector, error)
	// Update Connector on the fly
	UpdateConnector(context.Context, *Connector) (*Connector, error)
	// DeleteConnector deletes the corresponding connector
	DeleteConnector(context.Context, *DeleteConnectorReq) (*DeleteConnectorResp, error)
	// ListConnector lists the available connectors
	ListConnector(context.Context, *ListConnectorReq) (*ListConnectorResp, error)
}

func RegisterDexServer(s *grpc.Server, srv DexServer) {
	s.RegisterService(&_Dex_serviceDesc, srv)
}

func _Dex_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).CreateClient(ctx, req.(*CreateClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/UpdateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).UpdateClient(ctx, req.(*UpdateClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).DeleteClient(ctx, req.(*DeleteClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_CreatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).CreatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/CreatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).CreatePassword(ctx, req.(*CreatePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).UpdatePassword(ctx, req.(*UpdatePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/DeletePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).DeletePassword(ctx, req.(*DeletePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_ListPasswords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).ListPasswords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/ListPasswords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).ListPasswords(ctx, req.(*ListPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).GetVersion(ctx, req.(*VersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_ListRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRefreshReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).ListRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/ListRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).ListRefresh(ctx, req.(*ListRefreshReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_RevokeRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRefreshReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).RevokeRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/RevokeRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).RevokeRefresh(ctx, req.(*RevokeRefreshReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/VerifyPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).VerifyPassword(ctx, req.(*VerifyPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_CreateConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).CreateConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/CreateConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).CreateConnector(ctx, req.(*Connector))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_UpdateConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).UpdateConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/UpdateConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).UpdateConnector(ctx, req.(*Connector))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_DeleteConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).DeleteConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/DeleteConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).DeleteConnector(ctx, req.(*DeleteConnectorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dex_ListConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DexServer).ListConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dex/ListConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DexServer).ListConnector(ctx, req.(*ListConnectorReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Dex",
	HandlerType: (*DexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _Dex_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _Dex_UpdateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _Dex_DeleteClient_Handler,
		},
		{
			MethodName: "CreatePassword",
			Handler:    _Dex_CreatePassword_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Dex_UpdatePassword_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _Dex_DeletePassword_Handler,
		},
		{
			MethodName: "ListPasswords",
			Handler:    _Dex_ListPasswords_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Dex_GetVersion_Handler,
		},
		{
			MethodName: "ListRefresh",
			Handler:    _Dex_ListRefresh_Handler,
		},
		{
			MethodName: "RevokeRefresh",
			Handler:    _Dex_RevokeRefresh_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _Dex_VerifyPassword_Handler,
		},
		{
			MethodName: "CreateConnector",
			Handler:    _Dex_CreateConnector_Handler,
		},
		{
			MethodName: "UpdateConnector",
			Handler:    _Dex_UpdateConnector_Handler,
		},
		{
			MethodName: "DeleteConnector",
			Handler:    _Dex_DeleteConnector_Handler,
		},
		{
			MethodName: "ListConnector",
			Handler:    _Dex_ListConnector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1041 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xe9, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0x24, 0x5b, 0xa6, 0x46, 0xf7, 0xc6, 0x76, 0x18, 0x05, 0x05, 0x9c, 0x4d, 0x0b, 0x28,
	0x28, 0x20, 0x37, 0x0e, 0xd0, 0x02, 0x0d, 0x9a, 0x1e, 0x4a, 0xd2, 0x04, 0x68, 0x8b, 0x80, 0xa8,
	0xf2, 0xa7, 0x40, 0x05, 0x86, 0x1c, 0xd9, 0x44, 0x64, 0x92, 0xdd, 0xa5, 0x7c, 0xf4, 0x51, 0xfa,
	0x2a, 0xfd, 0xd5, 0x37, 0x2b, 0xf6, 0x20, 0xb5, 0x5c, 0x2a, 0x91, 0xf3, 0x8f, 0x33, 0x3b, 0xf3,
	0xcd, 0xb1, 0x33, 0x1f, 0x17, 0xba, 0x7e, 0x1a, 0x9d, 0xf8, 0x69, 0x34, 0x49, 0x59, 0x92, 0x25,
	0xa4, 0xe1, 0xa7, 0x11, 0xfd, 0xaf, 0x06, 0xcd, 0xe9, 0x32, 0xc2, 0x38, 0x23, 0x3d, 0xa8, 0x47,
	0xa1, 0x5b, 0x3b, 0xae, 0x8d, 0x5b, 0x5e, 0x3d, 0x0a, 0xc9, 0x11, 0x34, 0x39, 0x06, 0x0c, 0x33,
	0xb7, 0x2e, 0x75, 0x5a, 0x22, 0x0f, 0xa1, 0xcb, 0x30, 0x8c, 0x18, 0x06, 0xd9, 0x7c, 0xc5, 0x22,
	0xee, 0x36, 0x8e, 0x1b, 0xe3, 0x96, 0xd7, 0xc9, 0x95, 0x33, 0x16, 0x71, 0x61, 0x94, 0xb1, 0x15,
	0xcf, 0x30, 0x9c, 0xa7, 0x88, 0x8c, 0xbb, 0xbb, 0xca, 0x48, 0x2b, 0xdf, 0x08, 0x9d, 0x88, 0x90,
	0xae, 0xde, 0x2d, 0xa3, 0xc0, 0xdd, 0x3b, 0xae, 0x8d, 0x1d, 0x4f, 0x4b, 0x84, 0xc0, 0x6e, 0xec,
	0x5f, 0xa0, 0xdb, 0x94, 0x71, 0xe5, 0x37, 0xb9, 0x07, 0xce, 0x32, 0x39, 0x4b, 0xe6, 0x2b, 0xb6,
	0x74, 0xf7, 0xa5, 0x7e, 0x5f, 0xc8, 0x33, 0xb6, 0xa4, 0x7f, 0x40, 0x6b, 0x9a, 0xc4, 0x31, 0x06,
	0x59, 0xc2, 0x84, 0x6f, 0x76, 0x93, 0xa2, 0xae, 0x43, 0x7e, 0x17, 0x78, 0x75, 0x03, 0x4f, 0x55,
	0xdb, 0x30, 0xab, 0x0d, 0x92, 0x78, 0x11, 0x9d, 0xb9, 0xbb, 0xc7, 0xb5, 0x71, 0xc7, 0xd3, 0x12,
	0x9d, 0xc2, 0xf0, 0x97, 0x88, 0x67, 0x45, 0x00, 0x0f, 0x79, 0x4a, 0x26, 0x00, 0x41, 0xae, 0xe0,
	0x6e, 0xed, 0xb8, 0x31, 0x6e, 0x9f, 0xf6, 0x26, 0xa2, 0xb5, 0x6b, 0x3b, 0xc3, 0x82, 0x12, 0x18,
	0x58, 0x20, 0x7f, 0xd1, 0xcf, 0x81, 0x3c, 0xc7, 0x25, 0x66, 0x68, 0x6a, 0xed, 0x4b, 0xa0, 0x87,
	0x70, 0xa7, 0x62, 0xc5, 0x53, 0xfa, 0x35, 0xf4, 0xa7, 0x0c, 0xfd, 0x0c, 0xd5, 0xdd, 0x09, 0xcf,
	0x87, 0xd0, 0x0c, 0xa4, 0x20, 0xbd, 0xdb, 0xa7, 0x6d, 0x95, 0x8f, 0x3a, 0xd7, 0x47, 0xf4, 0x4f,
	0x18, 0x94, 0xfd, 0x78, 0x4a, 0xbe, 0x80, 0x9e, 0xbf, 0x64, 0xe8, 0x87, 0x37, 0x73, 0xbc, 0x8e,
	0x78, 0xc6, 0x25, 0x80, 0xe3, 0x75, 0xb5, 0xf6, 0x85, 0x54, 0x1a, 0xf8, 0xf5, 0x0f, 0xe3, 0x3f,
	0x80, 0xbe, 0x4e, 0xb7, 0xc8, 0xcb, 0xae, 0xe8, 0x04, 0x06, 0x65, 0x13, 0x9e, 0x92, 0xfb, 0xd0,
	0x8a, 0x93, 0x6c, 0xbe, 0x48, 0x56, 0x71, 0xa8, 0xa3, 0x3b, 0x71, 0x92, 0xbd, 0x14, 0x32, 0xfd,
	0xa7, 0x06, 0xfd, 0x59, 0x1a, 0xfa, 0x1f, 0x01, 0xad, 0xce, 0x64, 0xfd, 0x36, 0x33, 0xd9, 0xd8,
	0x30, 0x93, 0xf9, 0xac, 0xec, 0x7e, 0x60, 0xf6, 0xf6, 0xca, 0xb3, 0x77, 0x02, 0x83, 0x72, 0x6e,
	0xdb, 0xaa, 0x89, 0xc0, 0x79, 0xe3, 0x73, 0x7e, 0x95, 0xb0, 0x90, 0x1c, 0xc0, 0x1e, 0x5e, 0xf8,
	0xd1, 0x52, 0x17, 0xa2, 0x04, 0x91, 0xc1, 0xb9, 0xcf, 0xcf, 0x65, 0x9b, 0x3b, 0x9e, 0xfc, 0x26,
	0x23, 0x70, 0x56, 0x1c, 0x99, 0xcc, 0x4c, 0xcd, 0x6c, 0x21, 0x93, 0xbb, 0xb0, 0x2f, 0xbe, 0xe7,
	0x51, 0xa8, 0x93, 0x6e, 0x0a, 0xf1, 0x75, 0x48, 0x9f, 0xc1, 0x50, 0x5d, 0x76, 0x1e, 0x50, 0x74,
	0xee, 0x11, 0x38, 0xa9, 0x16, 0xf5, 0xa0, 0x74, 0xe5, 0x45, 0x16, 0x36, 0xc5, 0x31, 0x7d, 0x0a,
	0xc4, 0xf6, 0xbf, 0xf5, 0xb8, 0xd0, 0x33, 0x18, 0xaa, 0xc6, 0x98, 0xc1, 0x37, 0x17, 0x7c, 0x0f,
	0x9c, 0x18, 0xaf, 0xe6, 0x46, 0xd1, 0xfb, 0x31, 0x5e, 0xbd, 0x12, 0x75, 0x3f, 0x80, 0x8e, 0x38,
	0xb2, 0x6a, 0x6f, 0xc7, 0x78, 0x35, 0xd3, 0x2a, 0xfa, 0x18, 0x88, 0x1d, 0x68, 0xdb, 0x1d, 0x3c,
	0x82, 0xa1, 0x1a, 0xc1, 0xad, 0xb9, 0x09, 0x74, 0xdb, 0x74, 0x1b, 0xfa, 0x10, 0xfa, 0x62, 0xd9,
	0x0d, 0x6c, 0xfa, 0xbd, 0xda, 0xff, 0x12, 0xc6, 0x97, 0xd0, 0xca, 0x3b, 0x9d, 0x53, 0x88, 0x75,
	0x13, 0xeb, 0x73, 0xda, 0x01, 0x78, 0x8b, 0x8c, 0x47, 0x49, 0x2c, 0xe0, 0xbe, 0x81, 0x76, 0x21,
	0xf1, 0x54, 0x11, 0x35, 0xbb, 0x44, 0xa6, 0x53, 0xd7, 0x12, 0x19, 0x80, 0xa0, 0x78, 0xd9, 0xd2,
	0x3d, 0x4f, 0xb2, 0xfd, 0xdf, 0xd0, 0xf7, 0x70, 0xc1, 0x90, 0x9f, 0xff, 0x9e, 0xbc, 0xc7, 0xd8,
	0xc3, 0x45, 0x65, 0x93, 0xee, 0x43, 0x4b, 0xed, 0xb2, 0x98, 0x27, 0x45, 0x98, 0x8e, 0x52, 0xbc,
	0x0e, 0xc9, 0x67, 0x00, 0x81, 0x9c, 0x88, 0x70, 0xee, 0x67, 0x72, 0x15, 0x1a, 0x5e, 0x4b, 0x6b,
	0x7e, 0xcc, 0x84, 0xef, 0xd2, 0xe7, 0x99, 0xb8, 0xae, 0x50, 0x92, 0x77, 0xc3, 0x73, 0x84, 0x62,
	0xc6, 0x51, 0x34, 0xbd, 0x27, 0x7a, 0xa0, 0xe3, 0x8b, 0x8e, 0x1b, 0x83, 0x5b, 0x2b, 0x0d, 0xee,
	0x6f, 0xaa, 0x83, 0x85, 0x29, 0x4f, 0xc9, 0x53, 0xe8, 0x31, 0x25, 0xce, 0x33, 0x91, 0x7a, 0xde,
	0xb2, 0x03, 0xd9, 0x32, 0xab, 0x28, 0xaf, 0xcb, 0x0c, 0x05, 0xa7, 0xaf, 0x60, 0xe0, 0xe1, 0x65,
	0xf2, 0x1e, 0x6f, 0x11, 0xfc, 0xa3, 0x0d, 0xa0, 0x5f, 0xc1, 0xd0, 0x42, 0xda, 0x36, 0x0d, 0x2f,
	0x60, 0xf8, 0x16, 0x59, 0xb4, 0xb8, 0xd9, 0xbe, 0x07, 0x23, 0x63, 0x35, 0x75, 0xe0, 0x62, 0x17,
	0x7f, 0x05, 0x62, 0xc3, 0xf0, 0x54, 0x78, 0x5c, 0x0a, 0x6d, 0x84, 0x45, 0xe0, 0x5c, 0x2e, 0x67,
	0x55, 0x2f, 0x67, 0x75, 0xfa, 0xef, 0x3e, 0x34, 0x9e, 0xe3, 0x35, 0xf9, 0x0e, 0x3a, 0xe6, 0xff,
	0x80, 0xa8, 0x76, 0x5a, 0xbf, 0x96, 0xd1, 0xe1, 0x06, 0x2d, 0x4f, 0xe9, 0x8e, 0x70, 0x37, 0xd9,
	0x4f, 0xbb, 0x5b, 0x64, 0xad, 0xdd, 0x6d, 0x9a, 0x54, 0xee, 0xe6, 0xaf, 0x40, 0xbb, 0x5b, 0x3f,
	0x10, 0xed, 0x6e, 0xff, 0x33, 0xe8, 0x0e, 0x99, 0x42, 0xaf, 0xcc, 0x4f, 0xe4, 0xc8, 0x48, 0xd4,
	0xe8, 0xf7, 0xe8, 0xee, 0x46, 0x7d, 0x0e, 0x52, 0xa6, 0x0f, 0x0d, 0x52, 0x21, 0x2f, 0x0d, 0x52,
	0xe5, 0x1a, 0x05, 0x52, 0x66, 0x09, 0x0d, 0x52, 0x61, 0x19, 0x0d, 0x52, 0xa5, 0x14, 0xba, 0x43,
	0x9e, 0x41, 0xd7, 0x24, 0x09, 0xae, 0xdb, 0x61, 0x71, 0x89, 0x6e, 0x87, 0x4d, 0x27, 0x74, 0x87,
	0x3c, 0x06, 0xf8, 0x19, 0x33, 0x4d, 0x0c, 0xa4, 0x2f, 0xcd, 0xd6, 0xa4, 0x31, 0x1a, 0x94, 0x15,
	0xd2, 0xe5, 0x5b, 0x68, 0x1b, 0x8b, 0x46, 0xee, 0x14, 0xd0, 0xeb, 0x45, 0x19, 0x1d, 0x54, 0x95,
	0xd2, 0xf7, 0x07, 0xe8, 0x96, 0x56, 0x81, 0x1c, 0xea, 0x55, 0x2c, 0x2f, 0xda, 0xe8, 0x68, 0x93,
	0x3a, 0xef, 0x5a, 0x79, 0xa6, 0x75, 0xd7, 0x2a, 0xfb, 0xa2, 0xbb, 0x56, 0x5d, 0x00, 0xba, 0x43,
	0x9e, 0x14, 0x2f, 0xa1, 0xe2, 0x09, 0x68, 0xbd, 0xc4, 0x46, 0x96, 0xac, 0x9c, 0xf4, 0x38, 0x7e,
	0x82, 0xd3, 0xcb, 0xe2, 0x6d, 0x53, 0x38, 0x99, 0xb7, 0x69, 0x3e, 0xe3, 0x46, 0xee, 0xe6, 0x83,
	0xbc, 0x71, 0xa5, 0xc7, 0x20, 0x59, 0xdf, 0x68, 0x09, 0xe3, 0x68, 0x93, 0x5a, 0x20, 0xfc, 0x74,
	0x00, 0x24, 0x48, 0x2e, 0x26, 0x41, 0xc2, 0x30, 0xe1, 0x93, 0x10, 0xaf, 0x85, 0xe5, 0xbb, 0xa6,
	0x7c, 0xd6, 0x3f, 0xf9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x34, 0xdc, 0xd1, 0xe7, 0x0b, 0x00,
	0x00,
}
